################################################################################
#
# busybox_initramfs
#
################################################################################

GAMESTATION_INITRAMFS_VERSION = 1.24.2
GAMESTATION_INITRAMFS_SITE = http://www.busybox.net/downloads
GAMESTATION_INITRAMFS_SOURCE = busybox-$(GAMESTATION_INITRAMFS_VERSION).tar.bz2
GAMESTATION_INITRAMFS_LICENSE = GPLv2
GAMESTATION_INITRAMFS_LICENSE_FILES = LICENSE

GAMESTATION_INITRAMFS_CFLAGS = $(TARGET_CFLAGS)
GAMESTATION_INITRAMFS_LDFLAGS = $(TARGET_LDFLAGS)

GAMESTATION_INITRAMFS_KCONFIG_FILE = "$(GAMESTATION_INITRAMFS_PKGDIR)/busybox.config"

INITRAMFS_DIR=$(BINARIES_DIR)/initramfs

# Allows the build system to tweak CFLAGS
GAMESTATION_INITRAMFS_MAKE_ENV = \
	$(TARGET_MAKE_ENV) \
	CFLAGS="$(GAMESTATION_INITRAMFS_CFLAGS)"
GAMESTATION_INITRAMFS_MAKE_OPTS = \
	CC="$(TARGET_CC)" \
	ARCH=$(KERNEL_ARCH) \
	PREFIX="$(INITRAMFS_DIR)" \
	EXTRA_LDFLAGS="$(GAMESTATION_INITRAMFS_LDFLAGS)" \
	CROSS_COMPILE="$(TARGET_CROSS)" \
	CONFIG_PREFIX="$(INITRAMFS_DIR)" \
	SKIP_STRIP=y

GAMESTATION_INITRAMFS_KCONFIG_OPTS = $(GAMESTATION_INITRAMFS_MAKE_OPTS)

define GAMESTATION_INITRAMFS_BUILD_CMDS
	$(GAMESTATION_INITRAMFS_MAKE_ENV) $(MAKE) $(GAMESTATION_INITRAMFS_MAKE_OPTS) -C $(@D)
endef

define GAMESTATION_INITRAMFS_INSTALL_TARGET_CMDS
	mkdir -p $(INITRAMFS_DIR)/{new_root,sys,proc}
	cp $(GAMESTATION_INITRAMFS_PKGDIR)/init $(INITRAMFS_DIR)/init
	$(GAMESTATION_INITRAMFS_MAKE_ENV) $(MAKE) $(GAMESTATION_INITRAMFS_MAKE_OPTS) -C $(@D) install
	(cd $(INITRAMFS_DIR) && find . | cpio -H newc -o | gzip -9 > $(BINARIES_DIR)/initrd.gz)
endef

$(eval $(kconfig-package))
