#!/bin/bash

# Function to create connmann wifi profiles based on user settings

rb_wifi_boot_configure() {
        [ "$1" = "1" ] && X="" || X="$1"
        settings_ssid=`egrep "^wifi${X}.ssid" /boot/gamestation-backup.conf|sed "s/wifi${X}.ssid=//g"`
        settings_key=`egrep "^wifi${X}.key" /boot/gamestation-backup.conf|sed "s/wifi${X}.key=//g"`
        settings_file="/var/lib/connman/gamestation_wifi${X}.config"
        [ "$1" = "1" ] && settings_name="default" || settings_name="${X}"

        if [[ "$settings_ssid" != "" ]] ;then
	recallog "Recovering wifi for SSID: $settings_ssid"
        mkdir -p "/var/lib/connman"
        cat > "${settings_file}" <<EOF
[global]
Name=gamestation

[service_gamestation_${settings_name}]
Type=wifi
Name=${settings_ssid}
EOF
        if test "${settings_key}" != ""
        then
            settings_key_dec=$(/gamestation/scripts/gamestation-encode.sh decode "${settings_key}")
            echo "Passphrase=${settings_key_dec}" >> "${settings_file}"
	fi
    fi
}

# Main

case "$1" in
  start)
	if [ -f /boot/gamestation-backup.conf ]
	then
		if [ `egrep "^wifi.enabled" /boot/gamestation-backup.conf|sed "s/wifi.enabled=//g"` -ne 0  ]
		then
			recallog "Wifi option enabled, trying to configure"
			for i in {1..3}; do
				rb_wifi_boot_configure $i&
			done
			sleep 1 # wait a bit, otherwise, connman is not really started
			/usr/bin/connmanctl enable wifi || exit 1
			settings_region=`egrep "^wifi.region" /boot/gamestation-backup.conf|sed "s/wifi.region=//g"`
			if [[ "$settings_region" != "" ]] ;then
				recallog "Wifi region: ${settings_region}"
				/usr/sbin/iw reg set "${settings_region}"
			fi
			/usr/bin/connmanctl scan   wifi || exit 1
		else
			recallog "Wifi option disabled"
		fi
	else
		recallog "/boot/gamestation-backup.conf not found"
	fi

	# If share over network, let's add a timeout of 10 seconds (max) for slow networks
	if [ `grep -c "^sharedevice=NETWORK$" /boot/gamestation-boot.conf` -ne 0 ]
	then
		try=0
		until [ ! $try -lt 10 ]
		do
			if [ `ifconfig |grep -v "127.0.0.1"|grep -c "inet addr"` -gt 0 ]
			then
				break # Of course if network is OK, don't wait anymore!
			fi
			sleep 1
			try=`expr $try + 1`
		done
	fi
	;;
  stop)
	;;
  *)
esac

exit $?
